# Generated by Django 6.0 on 2026-01-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.FileField(upload_to='uploaded/')),
                ('converted', models.FileField(upload_to='converted/')),
                ('created_at', models.DateField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
