# Generated by Django 5.2.10 on 2026-02-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True)),
                ('from_format', models.CharField(default='', max_length=100)),
                ('to_format', models.CharField(default='', max_length=100)),
                ('created_at', models.DateField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConvertedMultiFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='converted/')),
                ('convert', models.ManyToManyField(blank=True, to='cloudConverterApp.convertmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UploadMultiFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded/')),
                ('convert', models.ManyToManyField(blank=True, to='cloudConverterApp.convertmodel')),
            ],
        ),
    ]
