# Generated by Django 6.0 on 2026-01-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudConverterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertmodel',
            name='from_format',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='convertmodel',
            name='to_format',
            field=models.CharField(default='', max_length=100),
        ),
    ]
