# Generated by Django 5.2.10 on 2026-01-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudConverterApp', '0002_convertmodel_from_format_convertmodel_to_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
