# Generated by Django 5.2.10 on 2026-02-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudConverterApp', '0002_contactusmodel_alter_convertedmultifilemodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
