# Generated by Django 5.2.10 on 2026-02-02 07:58

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='blog/')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(default='', max_length=100)),
                ('body', tinymce.models.HTMLField()),
                ('hash_tag', models.CharField(max_length=50)),
                ('author', models.CharField(default='DarkBytes', max_length=100)),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='blog.categorymodel')),
            ],
        ),
    ]
