# Generated by Django 5.2.10 on 2026-01-29 13:06

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='blog/')),
                ('heading', models.CharField(max_length=100, unique=True)),
                ('description', tinymce.models.HTMLField(max_length=500)),
            ],
        ),
    ]
