# Generated by Django 5.2.10 on 2026-02-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
