# Generated by Django 5.2.10 on 2026-01-30 06:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
